import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provide";
import {Wrapper} from "@/components/wrapper";
import {QueryProvider} from "@/components/query-client";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryProvider>
			<html lang="en">
				<body className={inter.className}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
						<Wrapper>{children}</Wrapper>
					</ThemeProvider>
				</body>
			</html>
		</QueryProvider>
	);
}
